language: python
python:
- "3.4"
- "3.5"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run plugtest.py
- coverage run -a coverage_test.py
- coverage run -a coverage_test_proxy.py
- coverage run -a coverage_test_reverse_proxy.py
- coverage run -a coverage_testIPv6.py
after_success:
- coveralls
